import IMAGES from "@/Images/Images";
import { WINDOW_TYPES } from "@/lib/providers/window";

export const icons = [
    {
        name: 'Launchpad',
        link: 'assets/launchpad.png',
        window: WINDOW_TYPES.LAUNCHPAD,
        image: IMAGES.launchpad,
        href: null,
    },
    {
        name: 'Home',
        link: 'assets/home.png',
        url: '/',
        href: null,
        image: IMAGES.home,
        window: WINDOW_TYPES.LAUNCHPAD,
    },
    {
        name: 'Work Experience',
        link: 'assets/job.png',
        redirect: false,
        url: '/work-experience',
        window: WINDOW_TYPES.WORK_EXPERIENCE,
        image: IMAGES.job,
        href: null,
    },
    {
        name: 'Resume',
        link: 'assets/resume.png',
        redirect: true,
        url: null,
        image: IMAGES.resume,
        window: WINDOW_TYPES.RESUME,
        href: 'https://drive.google.com/file/d/1sljq3K2hFlmDfTh3U2TpL2QGuQpkk_Or/view?usp=sharing',
    },
    {
        name: 'Projects',
        link: 'assets/project.png',
        redirect: false,
        url: '/projects',
        image: IMAGES.project,
        window: WINDOW_TYPES.PROJECTS,
        href: null,
    },
    {
        name: 'Github',
        link: 'assets/github.png',
        redirect: true,
        url: null,
        image: IMAGES.github,
        href: 'https://github.com/akhilphenom',
        window: WINDOW_TYPES.PROJECTS,
    },
    {
        name: 'LinkedIn',
        link: 'assets/linkedin.png',
        redirect: true,
        url: null,
        image: IMAGES.linkedin,
        href: 'https://www.linkedin.com/in/sai-akhil-katukam/',
        window: WINDOW_TYPES.LAUNCHPAD,
    },
    {
        name: 'Gmail',
        link: 'assets/gmail.png',
        redirect: true,
        url: null,
        image: IMAGES.gmail,
        href: `mailto:saiakhilk.katukam@gmail.com`,
        window: WINDOW_TYPES.GMAIL,
    },
]