const ICONS = {
    react : new URL('./react.svg', import.meta.url).href,
    expo : new URL('./expo.svg', import.meta.url).href,
    reactColored : new URL('./react-colored.svg', import.meta.url).href,
    reactNative : new URL('./react-native.svg', import.meta.url).href,
    tailwindcss : new URL('./tailwindcss.svg', import.meta.url).href,
    css : new URL('./css.svg', import.meta.url).href,
    scss : new URL('./scss.svg', import.meta.url).href,
    shadcn : new URL('./shadcn.svg', import.meta.url).href,
    framer : new URL('./framer.svg', import.meta.url).href,
    lottie : new URL('./lottie.svg', import.meta.url).href,
    html : new URL('./html.svg', import.meta.url).href,
    angular : new URL('./angular.svg', import.meta.url).href,
    mongo : new URL('./mongo.svg', import.meta.url).href,
    express : new URL('./express.svg', import.meta.url).href,
    nodejs : new URL('./nodejs.svg', import.meta.url).href,
    sql : new URL('./sql.svg', import.meta.url).href,
    redis : new URL('./redis.svg', import.meta.url).href,
    next : new URL('./next.svg', import.meta.url).href,
    cpp : new URL('./cpp.svg', import.meta.url).href,
    java : new URL('./java.svg', import.meta.url).href,
    mysql : new URL('./mysql.svg', import.meta.url).href,
    golang : new URL('./golang.svg', import.meta.url).href,
    angularmat : new URL('./angularmat.svg', import.meta.url).href,
    python : new URL('./python.svg', import.meta.url).href,
    js : new URL('./js.svg', import.meta.url).href,
    ts : new URL('./ts.svg', import.meta.url).href,
    lambda : new URL('./lambda.svg', import.meta.url).href,
    gateway : new URL('./gateway.svg', import.meta.url).href,
    sqs : new URL('./sqs.svg', import.meta.url).href,
    dynamodb : new URL('./dynamodb.svg', import.meta.url).href,
    route53 : new URL('./route53.svg', import.meta.url).href,
    gc : new URL('./gc.svg', import.meta.url).href,
    heroku : new URL('./heroku.svg', import.meta.url).href,
    s3 : new URL('./s3.svg', import.meta.url).href,
}
export default ICONS