const IMAGES = {
    launchpad : new URL('./launchpad.png', import.meta.url).href,
    home : new URL('./home.png', import.meta.url).href,
    gmail : new URL('./gmail.png', import.meta.url).href,
    github : new URL('./github.png', import.meta.url).href,
    find : new URL('./find.png', import.meta.url).href,
    job : new URL('./job.png', import.meta.url).href,
    resume : new URL('./resume.png', import.meta.url).href,
    project : new URL('./project.png', import.meta.url).href,
    workplace : new URL('./workplace.png', import.meta.url).href,
    youtube : new URL('./youtube.png', import.meta.url).href,
    publication : new URL('./publication.png', import.meta.url).href,
    leetcode : new URL('./leetcode.png', import.meta.url).href,
    linkedin : new URL('./linkedin.png', import.meta.url).href,
    hero : new URL('./stay-wild.jpg', import.meta.url).href,
    jeep : new URL('./jeep.png', import.meta.url).href,
    wild : new URL('./stay-wild.jpeg', import.meta.url).href,
    blackSnitch : new URL('./black-snitch.jpg', import.meta.url).href,
}
export default IMAGES